### ISSUE TITLE
Porting to Elden Ring

### ISSUE THREAD

**Issue by MatLCGPro** [GompDS/DS3PortingTool#1]
Would it be possilbe to make the tool port from Sekiro and DS3 to Elden Ring? How complicated would be to make that change?

**Comment by GompDS** [comment]
I don't think it's possible to do so with the current tools at my disposal. I rely on tools other people have made to port animations, ragdoll and cloth, so I I think I would need some version of those that go to Elden Ring (I haven't formally looked into it though). Plus its not really the purpose of this tool even if I knew it was possible. If we're talking non havok files, like flver, then maybe it could be done, but there isn't much point to that without the animations.

**Comment by MatLCGPro** [comment]
I understand, thank you! Your tool is awesome btw!

**Comment by MatLCGPro** [comment]
And to fix the models appearance, is there a recommended way to approach that? Is it just material configuration?

**Comment by GompDS** [comment]
First off, Sekiro and Elden Ring use a metallic workflow and Dark Souls 3 uses a specular workflow. So you'll need to take the textures from Elden Ring or Sekiro and convert them to a specular workflow before applying them to the ported ds3 enemy. Here's a guide I use for this, look for "Texture Conversion: Metalness to Specular": https://marmoset.co/posts/pbr-texture-conversion/
Also Elden Ring and Sekiro like to blend lots of textures together sometimes, the only solution here would be to bake the blends into one texture. After this it's a matter of choosing the correct mtds to use to get the right look. I made another tool called "Flver Fixer" which you'll need to use after changing mtds. Otherwise some meshes might be invisible due to buffer layouts. Overall it's a lot of trial and error, so you can see why I didn't attempt to automate it. People in the souls modding discord should be able to help you with texture issues if you ask.

**Comment by MatLCGPro** [comment]
Thank you very much! Very useful information! Sorry to bother 😅
